const fs = require("fs");
const path = require("path");

const DATA_DIR = path.join(__dirname, "..", "data");
const OUTPUT_FILE = path.join(__dirname, "..", "PROJECTS.md");

const files = fs
  .readdirSync(DATA_DIR)
  .filter((file) => file.endsWith(".json"));

let totalProjects = 0;

let markdown = `# 🚀 OpenSourceHub Projects

> Auto-generated from the \`data/\` directory.

Do not edit this file manually.

---

## 📊 Statistics

`;

for (const file of files) {
  const projects = JSON.parse(
    fs.readFileSync(path.join(DATA_DIR, file), "utf8")
  );

  totalProjects += projects.length;
}

markdown += `- Categories: ${files.length}
- Projects: ${totalProjects}

---

## 📚 Categories

`;

for (const file of files) {
  const category = path.basename(file, ".json");

  markdown += `- [${category}](#${category
    .toLowerCase()
    .replace(/\s+/g, "-")})\n`;
}

markdown += `\n---\n`;

for (const file of files) {
  const category = path.basename(file, ".json");

  const projects = JSON.parse(
    fs.readFileSync(path.join(DATA_DIR, file), "utf8")
  );

  markdown += `

# ${category}

| Project | Description | GitHub |
|----------|-------------|---------|
`;

  projects.forEach((project) => {
    markdown += `| ${project.name} | ${project.description} | [Repository](${project.github}) |\n`;
  });

  markdown += `\n`;
}

fs.writeFileSync(OUTPUT_FILE, markdown);

console.log(
  `✅ Generated PROJECTS.md (${totalProjects} projects across ${files.length} categories)`
);